---
Name: silverstripeproduct-catalogconfig
---
CatalogProduct:
  extensions:
    - FlexSlider
    - Dynamic\ViewableDataobject\Extensions\ViewableDataobject
SlideImage:
  extensions:
    - CatalogSlideImageDataExtension
CareCleaningDoc:
  extensions:
    - ProductDocsDataExtension
OperationManual:
  extensions:
    - ProductDocsDataExtension
SpecSheet:
  extensions:
    - ProductDocsDataExtension
Warranty:
  extensions:
    - ProductDocsDataExtension