---
Name: silverstripeproduct-catalogconfig
---
CatalogProduct:
  extensions:
    - FlexSlider
    - Dynamic\ViewableDataObject\Extensions\ViewableDataObject
SlideImage:
  extensions:
    - CatalogSlideImageDataExtension
CareCleaningDoc:
  extensions:
    - ProductDocDataExtension
OperationManual:
  extensions:
    - ProductDocDataExtension
SpecSheet:
  extensions:
    - ProductDocDataExtension
Warranty:
  extensions:
    - ProductDocDataExtension
ProductDocCollection_Controller:
  extensions:
    - CollectionExtension
    - ProductDocCollectionDataExtension