---
Name: silverstripeproduct-catalogconfig
---
CatalogProduct:
  extensions:
    - FlexSlider
    - Dynamic\ViewableDataobject\Extensions\ViewableDataobject
SlideImage:
  extensions:
    - CatalogSlideImageDataExtension