---
Name: silverstripeproduct-catalogconfig
---
Dynamic\ProductCatalog\ORM\CatalogProduct:
  extensions:
    - Dynamic\FlexSlider\ORM\FlexSlider
    - Dynamic\ViewableDataObject\Extensions\ViewableDataObject
    - SilverStripe\Versioned\Versioned('Stage','Live')
Dynamic\FlexSlider\Model\SlideImage:
  extensions:
    - Dynamic\ProductCatalog\ORM\CatalogSlideImageDataExtension
Dynamic\ProductCatalog\Docs\CareCleaningDoc:
  extensions:
    - Dynamic\ProductCatalog\ORM\ProductDocDataExtension
Dynamic\ProductCatalog\Docs\OperationManual:
  extensions:
    - Dynamic\ProductCatalog\ORM\ProductDocDataExtension
Dynamic\ProductCatalog\Docs\SpecSheet:
  extensions:
    - Dynamic\ProductCatalog\ORM\ProductDocDataExtension
Dynamic\ProductCatalog\Docs\Warranty:
  extensions:
    - Dynamic\ProductCatalog\ORM\ProductDocDataExtension
Dynamic\ProductCatalog\Page\ProductDocCollectionController:
  extensions:
    - Dynamic\Collection\CollectionExtension
    - Dynamic\ProductCatalog\ORM\ProductDocCollectionDataExtension